### ISSUE TITLE
Cannot install from Dockerfile. Old Node 12 (where 21 is current), general update required

### ISSUE THREAD

**Issue by vorenhoutgithub** [haroldtreen/epub-press#110]
## Current Behavior
git clone
Docker compose up (from within VSC) on docker-compose.yml
## Expected Behavior
Install to finish and containers to run
## Steps to reproduce
...
## System Information
Win 11 host/Docker Desktop
```
Executing task: docker compose -f "docker-compose.yaml" up -d --build 

time="2024-02-23T19:17:41+01:00" level=warning msg="The \"BASIC_AUTH_USERS\" variable is not set. Defaulting to a blank string."
[+] Running 33/3
 ✔ reverse-proxy 4 layers [⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                           5.3s 
 ✔ postgres 14 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                    26.9s 
 ✔ prometheus 12 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                    14.1s 
[+] Building 0.0s (0/0)  docker:default
[+] Building 71.8s (9/10)                                                                                                                               docker:default
 => [server internal] load build definition from Dockerfile                                                                                                       0.0s
 => => transferring dockerfile: 592B                                                                                                                              0.0s
 => [server internal] load metadata for docker.io/library/node:12                                                                                                 1.4s
 => [server internal] load .dockerignore                                                                                                                          0.1s
 => => transferring context: 232B                                                                                                                                 0.0s 
 => [server 1/6] FROM docker.io/library/node:12@sha256:01627afeb110b3054ba4a1405541ca095c8bfca1cb6f2be9479c767a2711879e                                          38.2s
 => => resolve docker.io/library/node:12@sha256:01627afeb110b3054ba4a1405541ca095c8bfca1cb6f2be9479c767a2711879e                                                  0.0s 
 => => sha256:9bed1e86f01ee95c76d2c8b4385a47ae336e6d293afade9368469d99daa9369f 11.30MB / 11.30MB                                                                  1.7s 
 => => sha256:6c8de432fc7f7d8c58899f61982d1662ec6b73fb3ef92f862ba170dcc5b64fa9 7.68kB / 7.68kB                                                                    0.0s 
 => => sha256:f5196cdf25181bc7e4411865a2e002932b7b6b0ffce787c04c1bdeaf1f204f20 45.43MB / 45.43MB                                                                 12.3s
 => => sha256:f44e4bdb3a6c1325cc4d40e585ed7a759127c0c87b0388ec0236b1698827d70d 4.34MB / 4.34MB                                                                    2.3s 
 => => sha256:01627afeb110b3054ba4a1405541ca095c8bfca1cb6f2be9479c767a2711879e 776B / 776B                                                                        0.0s
 => => sha256:3a69ea1270dbf4ef20477361be4b7a43400e559c6abdfaf69d73f7c755f434f5 2.21kB / 2.21kB                                                                    0.0s 
 => => sha256:2f75d131f4060950dd6cc1f580e2fa5504ece8d692113a9cdb0a866637b397d7 49.77MB / 49.77MB                                                                 11.3s 
 => => sha256:07dff4ad21ebdb3ce3e329699663b2f81af70152453025f6624584a39a8e22b6 214.48MB / 214.48MB                                                               30.9s 
 => => sha256:e0ac4f13b766d321acc3b650d3d23b82828995711f6f247ff591722c00d04cec 4.19kB / 4.19kB                                                                   11.8s 
 => => sha256:df2c3b2eb7cc63351bb32f26457bbe0402af8082548f26975f0c329bc7841881 23.70MB / 23.70MB                                                                 16.8s 
 => => extracting sha256:f5196cdf25181bc7e4411865a2e002932b7b6b0ffce787c04c1bdeaf1f204f20                                                                         1.8s 
 => => sha256:efe636eac583776a8a114d50fef15bc65b648f3d2bb53326cf1f21cc5ef2b3ae 2.34MB / 2.34MB                                                                   12.9s 
 => => sha256:fe17849545bb51455d3f7c8773ded2dbb1d6668a85bd00564573a4b88afd36f6 464B / 464B                                                                       13.1s 
 => => extracting sha256:9bed1e86f01ee95c76d2c8b4385a47ae336e6d293afade9368469d99daa9369f                                                                         0.3s 
 => => extracting sha256:f44e4bdb3a6c1325cc4d40e585ed7a759127c0c87b0388ec0236b1698827d70d                                                                         0.1s 
 => => extracting sha256:2f75d131f4060950dd6cc1f580e2fa5504ece8d692113a9cdb0a866637b397d7                                                                         2.0s 
 => => extracting sha256:07dff4ad21ebdb3ce3e329699663b2f81af70152453025f6624584a39a8e22b6                                                                         5.5s 
 => => extracting sha256:e0ac4f13b766d321acc3b650d3d23b82828995711f6f247ff591722c00d04cec                                                                         0.0s 
 => => extracting sha256:df2c3b2eb7cc63351bb32f26457bbe0402af8082548f26975f0c329bc7841881                                                                         1.3s 
 => => extracting sha256:efe636eac583776a8a114d50fef15bc65b648f3d2bb53326cf1f21cc5ef2b3ae                                                                         0.0s 
 => => extracting sha256:fe17849545bb51455d3f7c8773ded2dbb1d6668a85bd00564573a4b88afd36f6                                                                         0.0s 
 => [server internal] load build context                                                                                                                          1.3s 
 => => transferring context: 58.73MB                                                                                                                              1.3s 
 => [server 2/6] WORKDIR /usr/src/epub-press                                                                                                                      0.4s 
 => [server 3/6] COPY package.json package-lock.json ./                                                                                                           0.1s 
 => [server 4/6] RUN npm install --production                                                                                                                    30.3s 
 => ERROR [server 5/6] RUN if [ "calibre" = "calibre" ] ; then apt-get update && apt-get install -y libgl1-mesa-glx && wget -nv -O- https://download.calibre-ebo  1.2s 
------
 > [server 5/6] RUN if [ "calibre" = "calibre" ] ; then apt-get update && apt-get install -y libgl1-mesa-glx && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin install_dir=calibre-bin/ isolated=y ; fi:
0.480 Ign:1 http://security.debian.org/debian-security stretch/updates InRelease
0.483 Ign:2 http://deb.debian.org/debian stretch InRelease
0.508 Ign:3 http://deb.debian.org/debian stretch-updates InRelease
0.509 Ign:4 http://security.debian.org/debian-security stretch/updates Release
0.537 Ign:5 http://deb.debian.org/debian stretch Release
0.537 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.563 Ign:7 http://deb.debian.org/debian stretch-updates Release
0.566 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
0.588 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.598 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.614 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.633 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
0.639 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.671 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.689 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
0.699 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
0.714 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.733 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.738 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.759 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
0.764 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.786 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.788 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
0.814 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.818 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
0.840 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.844 Err:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
0.844   404  Not Found
0.867 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.870 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
0.893 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
0.917 Ign:9 http://deb.debian.org/debian stretch/main all Packages
0.942 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
0.967 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.990 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
1.014 Ign:9 http://deb.debian.org/debian stretch/main all Packages
1.038 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
1.063 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
1.090 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
1.115 Ign:9 http://deb.debian.org/debian stretch/main all Packages
1.139 Err:10 http://deb.debian.org/debian stretch/main amd64 Packages
1.139   404  Not Found
1.165 Err:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
1.165   404  Not Found
1.189 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
1.192 Reading package lists...
1.198 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
1.198 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
1.198 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
1.198 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found
1.198 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
1.198 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
1.198 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
failed to solve: process "/bin/sh -c if [ \"$converter\" = \"calibre\" ] ; then apt-get update && apt-get install -y libgl1-mesa-glx && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin install_dir=calibre-bin/ isolated=y ; fi" did not complete successfully: exit code: 100
```
## Tried
Oldest available node: 18;
Current Node 21 See https://hub.docker.com/_/node/
But fails with packages.
21:
```
0.347 npm WARN config production Use `--omit=dev` instead.
0.810 npm WARN old lockfile
0.810 npm WARN old lockfile The package-lock.json file was created with an old version of npm,
0.810 npm WARN old lockfile so supplemental metadata must be fetched from the registry.
0.810 npm WARN old lockfile
0.810 npm WARN old lockfile This is a one-time fix-up, please be patient...
0.810 npm WARN old lockfile
12.75 npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
12.77 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
12.78 npm WARN deprecated request-promise@4.2.5: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
12.79 npm WARN deprecated shortid@2.2.15: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
12.95 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
12.99 npm WARN deprecated phin@2.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
13.24 npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
13.35 npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
13.37 npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
13.58 npm WARN deprecated is-buffer@1.1.5: This version of 'is-buffer' is out-of-date. You must update to v1.1.6 or newer
13.61 npm WARN deprecated sequelize@5.21.7: Please update to v6 or higher! A migration guide can be found here: https://sequelize.org/v6/manual/upgrade-to-v6.html     
13.68 npm WARN deprecated har-validator@5.1.3: this library is no longer supported
14.06 npm WARN deprecated domelementtype@1.3.0: update to domelementtype@1.3.1
14.21 npm WARN deprecated buildmail@4.0.1: This project is unmaintained
14.85 npm WARN deprecated core-js@3.6.5: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
15.97 npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
16.56 npm WARN deprecated core-js@2.5.3: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
19.28 npm notice
19.28 npm notice New minor version of npm available! 10.2.4 -> 10.4.0
19.28 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
19.28 npm notice Run `npm install -g npm@10.4.0` to update!
19.28 npm notice
19.28 npm ERR! code 1
19.28 npm ERR! path /usr/src/epub-press/node_modules/sqlite3
19.28 npm ERR! command failed
19.28 npm ERR! command sh -c node-pre-gyp install --fallback-to-build
19.28 npm ERR! make: Entering directory '/usr/src/epub-press/node_modules/sqlite3/build'
19.28 npm ERR!   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
19.28 npm ERR! make: Leaving directory '/usr/src/epub-press/node_modules/sqlite3/build'
19.28 npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/src/epub-press/node_modules/sqlite3/lib/binding/node-v120-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/src/epub-press/node_modules/sqlite3/lib/binding/node-v120-linux-x64 --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)
19.28 npm ERR! node-pre-gyp info it worked if it ends with ok
19.28 npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
19.28 npm ERR! node-pre-gyp info using node@21.6.2 | linux | x64
19.28 npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
19.28 npm ERR! (node:19) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
19.28 npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
19.28 npm ERR! node-pre-gyp info check checked for "/usr/src/epub-press/node_modules/sqlite3/lib/binding/node-v120-linux-x64/node_sqlite3.node" (not found)
19.28 npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v120-linux-x64.tar.gz
19.28 npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v120-linux-x64.tar.gz
19.28 npm ERR! node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v120-linux-x64.tar.gz
19.28 npm ERR! node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@21.6.2 (node-v120 ABI, glibc) (falling back to source compile with node-gyp)  
19.28 npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v120-linux-x64.tar.gz
19.28 npm ERR! gyp info it worked if it ends with ok
19.28 npm ERR! gyp info using node-gyp@10.0.1
19.28 npm ERR! gyp info using node@21.6.2 | linux | x64
19.28 npm ERR! gyp info ok
19.28 npm ERR! gyp info it worked if it ends with ok
19.28 npm ERR! gyp info using node-gyp@10.0.1
19.28 npm ERR! gyp info using node@21.6.2 | linux | x64
19.28 npm ERR! gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
19.28 npm ERR! gyp http GET https://nodejs.org/download/release/v21.6.2/node-v21.6.2-headers.tar.gz
19.28 npm ERR! gyp http 200 https://nodejs.org/download/release/v21.6.2/node-v21.6.2-headers.tar.gz
19.28 npm ERR! gyp http GET https://nodejs.org/download/release/v21.6.2/SHASUMS256.txt
19.28 npm ERR! gyp http 200 https://nodejs.org/download/release/v21.6.2/SHASUMS256.txt
19.28 npm ERR! gyp info spawn /usr/bin/python3
19.28 npm ERR! gyp info spawn args [
19.28 npm ERR! gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
19.28 npm ERR! gyp info spawn args 'binding.gyp',
19.28 npm ERR! gyp info spawn args '-f',
19.28 npm ERR! gyp info spawn args 'make',
19.28 npm ERR! gyp info spawn args '-I',
19.28 npm ERR! gyp info spawn args '/usr/src/epub-press/node_modules/sqlite3/build/config.gypi',
19.28 npm ERR! gyp info spawn args '-I',
19.28 npm ERR! gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
19.28 npm ERR! gyp info spawn args '-I',
19.28 npm ERR! gyp info spawn args '/root/.cache/node-gyp/21.6.2/include/node/common.gypi',
19.28 npm ERR! gyp info spawn args '-Dlibrary=shared_library',
19.28 npm ERR! gyp info spawn args '-Dvisibility=default',
19.28 npm ERR! gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/21.6.2',
19.28 npm ERR! gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
19.28 npm ERR! gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/21.6.2/<(target_arch)/node.lib',
19.28 npm ERR! gyp info spawn args '-Dmodule_root_dir=/usr/src/epub-press/node_modules/sqlite3',
19.28 npm ERR! gyp info spawn args '-Dnode_engine=v8',
19.28 npm ERR! gyp info spawn args '--depth=.',
19.28 npm ERR! gyp info spawn args '--no-parallel',
19.28 npm ERR! gyp info spawn args '--generator-output',
19.28 npm ERR! gyp info spawn args 'build',
19.28 npm ERR! gyp info spawn args '-Goutput_dir=.'
19.28 npm ERR! gyp info spawn args ]
19.28 npm ERR! gyp info ok
19.28 npm ERR! gyp info it worked if it ends with ok
19.28 npm ERR! gyp info using node-gyp@10.0.1
19.28 npm ERR! gyp info using node@21.6.2 | linux | x64
19.28 npm ERR! gyp info spawn make
19.28 npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
19.28 npm ERR! /bin/sh: 1: python: not found
19.28 npm ERR! make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127
19.28 npm ERR! gyp ERR! build error
19.28 npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
19.28 npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
19.28 npm ERR! gyp ERR! System Linux 5.15.133.1-microsoft-standard-WSL2
19.28 npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/src/epub-press/node_modules/sqlite3/lib/binding/node-v120-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/src/epub-press/node_modules/sqlite3/lib/binding/node-v120-linux-x64" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v120"
19.28 npm ERR! gyp ERR! cwd /usr/src/epub-press/node_modules/sqlite3
19.28 npm ERR! gyp ERR! node -v v21.6.2
19.28 npm ERR! gyp ERR! node-gyp -v v10.0.1
19.28 npm ERR! gyp ERR! not ok
19.28 npm ERR! node-pre-gyp ERR! build error
19.28 npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/src/epub-press/node_modules/sqlite3/lib/binding/node-v120-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/src/epub-press/node_modules/sqlite3/lib/binding/node-v120-linux-x64 --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)
19.28 npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/epub-press/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
19.28 npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
19.28 npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
19.28 npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
19.28 npm ERR! node-pre-gyp ERR! System Linux 5.15.133.1-microsoft-standard-WSL2
19.28 npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/epub-press/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
19.28 npm ERR! node-pre-gyp ERR! cwd /usr/src/epub-press/node_modules/sqlite3
19.28 npm ERR! node-pre-gyp ERR! node -v v21.6.2
19.28 npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
19.28 npm ERR! node-pre-gyp ERR! not ok
19.29
19.29 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-02-23T18_27_14_217Z-debug-0.log
------
failed to solve: process "/bin/sh -c npm install --production" did not complete successfully: exit code: 1
```

**Comment by sanujar** [comment]
I think this issue may be related to the Calibre installation code behaving
in an unexpected manner.

To skip that step for troubleshooting purposes, please try and set the
build arguments for the variable "converter" to "kindlegen". I think there
are instructions relating to this towards the bottom of the README.

**Comment by vorenhoutgithub** [comment]
That does indeed remove the error when using the ancient and unsupported node:12
So this issue is basically a call to upgrade ;)
That will also fix all the calls/merge requests from the bot here.
